[package]
name = "arrow"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-epoch = "0.9"
crossbeam-utils = "0.8"

[dev-dependencies]
anyhow = "1.0"
tempfile = "3.23"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(coverage,coverage_nightly)',
] }
